---
# tasks file for perfsonar-archive

- name: Configure esmond archive for perfSONAR
  tags: [ 'ps::config' ]
  command: /usr/lib/perfsonar/scripts/system_environment/configure_esmond new

- name: Add list of write-access authorised IP addresses to esmond archive
  tags: [ 'ps::config' ]
  command: >
    /usr/sbin/esmond_manage add_user_ip_address
    "{{ perfsonar_archiver_auth_user }}" "{{ item }}"
  with_items: "{{ perfsonar_archiver_auth_ipv4_addresses | default([]) }}"
